dataset_info = dict(
    dataset_name="mice",
    paper_info=dict(),  # TODO publish this dataset
    keypoint_info={
        0: dict(name="Snout", id=0, type="upper", swap=""),
        1: dict(name="Right Ear", id=1, type="upper", swap="Left Ear"),
        2: dict(name="Right Leg", id=2, type="lower", swap="Left Leg"),
        3: dict(name="Left Leg", id=3, type="lower", swap="Right Leg"),
        4: dict(name="Left Ear", id=4, type="upper", swap="Right Ear"),
        5: dict(name="Centroid", id=5, type="lower", swap=""),
        6: dict(name="Base of Tail", id=6, type="lower", swap=""),
        7: dict(name="Tailtag", id=7, type="lower", swap=""),
    },
    skeleton_info={
        0: dict(link=("Snout", "Right Ear"), id=0),
        1: dict(link=("Snout", "Left Ear"), id=1),
        2: dict(link=("Right Ear", "Centroid"), id=2),
        3: dict(link=("Left Ear", "Centroid"), id=3),
        4: dict(link=("Centroid", "Right Leg"), id=4),
        5: dict(link=("Centroid", "Left Leg"), id=5),
        6: dict(link=("Right Leg", "Base of Tail"), id=6),
        7: dict(link=("Left Leg", "Base of Tail"), id=7),
        8: dict(link=("Base of Tail", "Tailtag"), id=8),
    },
    joint_weights=[
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
    ],
    sigmas=[
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
    ],
    classes=["mouse"],
    actions=[
        "Other",
        "Running",
        "Interacting",
        "Rearing",
        "Grooming",
    ],
)
